spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/xxi?useSSL=false"
    username: "admin"
    password: "12345"
    driver-class-name: "com.mysql.cj.jdbc.Driver"
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: create